name:  Prod

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,5'

permissions:
  contents: read
  id-token: write

jobs:
  get-image-name:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4
      - id: image-name
        run: |
          image="$(make p2p-image)"
          echo "Image name: '$image'"
          echo "image_name=$image" >> $GITHUB_OUTPUT

  get-latest-version:
    needs: [get-image-name]
    uses: coreeng/p2p/.github/workflows/p2p-get-latest-image-prod.yaml@v1
    with:
      image-name: ${{ needs.get-image-name.outputs.image-name }}

  prod:
    needs: [get-latest-version]
    uses: coreeng/p2p/.github/workflows/p2p-workflow-prod.yaml@v1
    with:
      version: ${{ needs.get-latest-version.outputs.version }}